USE [master]
GO

/****** Object:  Database [WRI]    Script Date: 4/6/2015 1:34:14 PM ******/
CREATE DATABASE [WRI]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'WRI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WRI.mdf' , SIZE = 35840KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON
( NAME = N'WRI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WRI_log.ldf' , SIZE = 10176KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WRI] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WRI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WRI] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [WRI] SET ANSI_NULLS OFF
GO

ALTER DATABASE [WRI] SET ANSI_PADDING OFF
GO

ALTER DATABASE [WRI] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [WRI] SET ARITHABORT OFF
GO

ALTER DATABASE [WRI] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [WRI] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [WRI] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [WRI] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [WRI] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [WRI] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [WRI] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [WRI] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [WRI] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [WRI] SET  DISABLE_BROKER
GO

ALTER DATABASE [WRI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [WRI] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [WRI] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [WRI] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [WRI] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [WRI] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [WRI] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [WRI] SET RECOVERY FULL
GO

ALTER DATABASE [WRI] SET  MULTI_USER
GO

ALTER DATABASE [WRI] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [WRI] SET DB_CHAINING OFF
GO

ALTER DATABASE [WRI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [WRI] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [WRI] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [WRI] SET  READ_WRITE
GO
