USE [master]
GO

/****** Object:  Database [WRI_Spatial]    Script Date: 4/6/2015 1:34:14 PM ******/
CREATE DATABASE [WRI_Spatial]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WRI_Spatial', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WRI_Spatial.mdf' , SIZE = 35840KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WRI_Spatial_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WRI_Spatial_log.ldf' , SIZE = 10176KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WRI_Spatial] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WRI_Spatial].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WRI_Spatial] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WRI_Spatial] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WRI_Spatial] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WRI_Spatial] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WRI_Spatial] SET ARITHABORT OFF 
GO

ALTER DATABASE [WRI_Spatial] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WRI_Spatial] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WRI_Spatial] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WRI_Spatial] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WRI_Spatial] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WRI_Spatial] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WRI_Spatial] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WRI_Spatial] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WRI_Spatial] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WRI_Spatial] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WRI_Spatial] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WRI_Spatial] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WRI_Spatial] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WRI_Spatial] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WRI_Spatial] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WRI_Spatial] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WRI_Spatial] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WRI_Spatial] SET RECOVERY FULL 
GO

ALTER DATABASE [WRI_Spatial] SET  MULTI_USER 
GO

ALTER DATABASE [WRI_Spatial] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WRI_Spatial] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WRI_Spatial] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WRI_Spatial] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WRI_Spatial] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WRI_Spatial] SET  READ_WRITE 
GO


